version: "3.3"

services:
  app:
    image: request-store:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - pg
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - .:/app
    command: sh -c './scripts/wait-for-it.sh pg:${POSTGRES_PORT} -- npm start'

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  lb:
    image: nginx-loadbalancer:latest
    build:
      context: .
      dockerfile: load_balancer.Dockerfile
    environment:
      - PROXY_UPSTREAM
    depends_on:
      - app
    ports:
      - "3000:80"
